name: Go package
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
           java-version: 1.11
      - name: setup java
        run: 
         javac trimukesh.java
         java trimukesh
         
  test:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - name: actions
      - uses: dawidd6/action-ansible-playbook@v1
      - name: run ansible playbook
        run: ansible-playbook demo.yaml
