name: Go package

on:
  push:
    paths:
      - './trimukesh.java'
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: Display the path
        run: ./trimukesh.java
