name: Go package
on:
  push:
    paths:
      - 'helloworld.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Display the path
        run: echo $paths
