name: Hello

on: [push, pull_request]
jobs:
 test:
   name: javaprogram
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
           java-version: 1.11
      - name: setup java
        run: |
           javac trimukesh.java
           java trimukesh
           ansible-playbook demo.yaml
