name: Test PowerShell on Ubuntu
on: push
jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module SqlServer, PSScriptAnalyzer
