
name: CI

on:

  push:
    branches: [main]


 
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted
    defaults:
      run:
        shell: bash
  

    steps:
      - uses: actions/checkout@v1
      - name: Verify basic
        run: helloworld.js
