name: Hello

on: [push, pull_request]
jobs:
 test:
   name: javaprogram
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-ansible-playbook@v2
      - name: run ansible playbook
        run: ansible-playbook demo.yaml
