
name: CI

on:

  push:
    branches: [main]


 
  workflow_dispatch:

jobs:

  build:

    runs-on: self-hosted
    defaults:
      run:
        shell: java
  

    steps:
      - uses: actions/checkout@v1

      - name: Run a one-line script
        run: echo helloworld.
      - name: Verify basic
        run: helloworld.js --archive

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
