name: Update Secret
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to update'
        required: true
      new_value:
        description: 'New value for the secret'
        required: true
jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Secret
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const secretName = '${{ github.event.inputs.secret_name }}';
            const newValue = '${{ github.event.inputs.new_value }}';
            octokit.actions.updateSecretForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              secret_name: secretName,
              encrypted_value: Buffer.from(newValue).toString('base64')
            });
