name: Update Secret
on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret to update'
        required: true
      new_value:
        description: 'New value for the secret'
        required: true
jobs:
  update-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update Secret
        run: |
          # Set the secret name and new value
          SECRET_NAME=${{ github.event.inputs.secret_name }}
          NEW_VALUE=${{ github.event.inputs.new_value }}
          # Make the API request to update the secret
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"encrypted_value\":\"$(echo -n $NEW_VALUE | base64)\"}" \
            "https://api.github.com/Trimukesh/${{ github.repository }}/actions/secrets/${SECRET_NAME}"
